


	select 
		Min(order_date) first_order_date,
		Max(order_date) last_order_date,
		Min(due_date) first_due_date,
		Max(due_date) last_due_date,
		Min(shipping_date) first_ship_date,
		Max(shipping_date) last_ship_date
		from gold.fact_sales

-- Find the Total Sales
	select 
		sum(sales_amount) as total_sales
	from gold.fact_sales

-- Find how many items are sold

	select 
		sum(quantity) as total_items
	from gold.fact_sales


-- Find the average selling price

	select 
		avg(price) as average_price
	from gold.fact_sales


-- Find the Total number of Orders

	select 
		count(distinct(order_number)) as total_orders
	from gold.fact_sales


-- Find the total number of products

	select 
		count(product_key) as total_products
	from gold.dim_products

-- Find the total number of customers

	select 
		count(customer_key) as total_cx
	from gold.dim_customers

-- Find the total number of customers that has placed an order

	select 
		count(distinct(customer_key)) as total_cx_orders_placed
	from gold.fact_sales

--Generate a report that shows all key metrics of the business

	select 'Total Sales' as measure_name, SUM(sales_amount) as measure_value from gold.fact_sales
	union all
	select 'Total Quantity' as measure_name, SUM(quantity) as measure_value from gold.fact_sales
	union all
	select 'Total Cx' as measure_name, count(distinct customer_key) as measure_value from gold.dim_customers
	union all
	select 'Total Orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
	union all
	select 'Average Price' as measure_name, avg(price) as measure_value from gold.fact_sales
	union all
	select 'Total Products' as measure_name, sum(distinct product_key) as measure_value from gold.dim_products

-- Find total customers by countries

	select 
	country,
	count(customer_key) as total_cx_by_country
	from gold.dim_customers
	group by country

-- Find total customers by gender

	select 
	gender,
	count(customer_key) as total_cx_by_gender
	from gold.dim_customers
	group by gender

-- Find total products by category

	select 
	category,
	count(product_name) as total_products_by_category
	from gold.dim_products
	group by category
	order by total_products_by_category desc

-- What is the average costs in each category?

	select 
	category,
	avg(cost) as avg_cost_by_category
	from gold.dim_products
	group by category
	order by avg_cost_by_category desc

-- What is the total revenue generated for each category?

	select 
	p.category,
	sum(f.sales_amount) as total_rev_by_category
	from gold.fact_sales f
	left join gold.dim_products p
	on p.product_key = f.product_key
	group by p.category 
	order by total_rev_by_category desc

-- Find total revenue is generated by each customer

select 
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_rev_by_Cx
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key = f.customer_key
	group by 
		c.customer_key,
		c.first_name,
		c.last_name
	order by total_rev_by_Cx desc

-- What is the distribution of sold items across countries?

select 
	c.country,
	sum(f.quantity) as total_sold_item_by_country
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key = f.customer_key
	group by 
		c.country
	order by total_sold_item_by_country desc

*/

-- Which 5 products generate the highest revenue?

	select top 5
	p.product_name,
	sum(f.sales_amount) as top_5_highest_revenue
	from gold.fact_sales f
	left join gold.dim_products p
	on p.product_key = f.product_key
	group by p.product_name 
	order by top_5_highest_revenue desc


-- What are the 5 worst-performing products in terms of sales?

	select top 5
	p.product_name,
	sum(f.sales_amount) as top_5_highest_revenue
	from gold.fact_sales f
	left join gold.dim_products p
	on p.product_key = f.product_key
	group by p.product_name 
	order by top_5_highest_revenue 
